insert into authors (name, gender, country) values ('Pet Honniebal', 'F', 'China');
insert into authors (name, gender, country) values ('Korella Zylbermann', 'M', 'China');
insert into authors (name, gender, country) values ('Rowney Pridie', 'F', 'Brazil');
insert into authors (name, gender, country) values ('Ailyn Quigley', 'F', 'United States');
insert into authors (name, gender, country) values ('Cassy Fey', 'F', 'China');
insert into authors (name, gender, country) values ('Nealy Linder', 'F', 'China');
insert into authors (name, gender, country) values ('Sharona Mugg', 'M', 'Brazil');
insert into authors (name, gender, country) values ('Rabi Rains', 'M', 'China');
insert into authors (name, gender, country) values ('Ame de Werk', 'M', 'United States');
insert into authors (name, gender, country) values ('Melly Horlick', 'F', 'China');
insert into authors (name, gender, country) values ('Noreen Dawdary', 'M', 'France');
insert into authors (name, gender, country) values ('Sheppard Paulucci', 'F', 'France');
insert into authors (name, gender, country) values ('Pattie Murra', 'F', 'China');
insert into authors (name, gender, country) values ('Kristofer Zorzenoni', 'F', 'China');
insert into authors (name, gender, country) values ('Keen Gerritzen', 'M', 'China');
insert into authors (name, gender, country) values ('Jed Antonsson', 'F', 'China');
insert into authors (name, gender, country) values ('Kira Padly', 'F', 'United States');
insert into authors (name, gender, country) values ('Stefania Franken', 'F', 'France');
insert into authors (name, gender, country) values ('Katey Mitham', 'M', 'Russia');
insert into authors (name, gender, country) values ('Abby Adelsberg', 'M', 'China');
insert into authors (name, gender, country) values ('Goldie Carnachen', 'F', 'China');
insert into authors (name, gender, country) values ('Redd Olivetti', 'F', 'China');
insert into authors (name, gender, country) values ('Hortense McCarty', 'M', 'Brazil');
insert into authors (name, gender, country) values ('Mason Mitchel', 'M', 'China');
insert into authors (name, gender, country) values ('Shannon Clout', 'F', 'China');
insert into authors (name, gender, country) values ('Claudetta Djurevic', 'F', 'Russia');
insert into authors (name, gender, country) values ('Deck Semor', 'M', 'China');
insert into authors (name, gender, country) values ('Caresse Deeman', 'M', 'China');
insert into authors (name, gender, country) values ('Leilah Bischoff', 'M', 'China');
insert into authors (name, gender, country) values ('Jacquetta Volks', 'M', 'China');
insert into authors (name, gender, country) values ('Frasier Berntsson', 'F', 'China');
insert into authors (name, gender, country) values ('Chico Pywell', 'F', 'China');
insert into authors (name, gender, country) values ('Aaron Chopping', 'M', 'China');
insert into authors (name, gender, country) values ('Sallyanne Petri', 'F', 'China');
insert into authors (name, gender, country) values ('Olivier Sparkwell', 'F', 'China');